services:
  toxcbt:
    build: .
    container_name: toxcbt
    restart: unless-stopped
    environment:
      TOX_NAME: "go-tox-bot"
      TOX_STATUS: "ololo"
      TOX_DATA_DIR: "/data"
      TOX_SAVEDATA: "/data/bot.tox"
      TOX_BOOTSTRAP_NODES: "tox.abilinski.com:33445:10C00EB250C3233E343E2AEBA07115A5C28920E9C8D29492F6D00B29049EDC7E,144.217.167.73:33445:7E5668E0EE09E19F320AD47902419331FFEE147BB3606769CFBE921A2A2FD34C"
    volumes:
      - ./data:/data
